name = "pyfortran"
version = "0.1.0"
license = "license"
author = "Jane Doe"
maintainer = "jane.doe@example.com"
copyright = "Copyright 2022, Jane Doe"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false

[dependencies]
pyplot-fortran.git = "https://github.com/jacobwilliams/pyplot-fortran"
pyplot-fortran.tag = "3.2.0"
